# Generated by Django 5.1.4 on 2024-12-16 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_subscriptiontype_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('open_ai_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Тип запроса',
                'verbose_name_plural': 'Типы запроса',
            },
        ),
        migrations.CreateModel(
            name='AIModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'ИИ Модель',
                'verbose_name_plural': 'ИИ Модели',
            },
        ),
        migrations.AlterModelOptions(
            name='useraction',
            options={'verbose_name': 'Действие пользователя', 'verbose_name_plural': 'Действия пользователя'},
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='referal',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.telegramuser'),
        ),
        migrations.AddField(
            model_name='useraction',
            name='input_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useraction',
            name='output_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useraction',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraction',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.telegramuser'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.telegramuser'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='sub_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.subscriptiontype'),
        ),
        migrations.AddField(
            model_name='useraction',
            name='action_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.actiontype'),
        ),
        migrations.AddField(
            model_name='useraction',
            name='model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.aimodels'),
        ),
    ]
