# Generated by Django 5.1.4 on 2024-12-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_actiontype_aimodels_alter_useraction_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actiontype',
            name='open_ai_name',
        ),
        migrations.AddField(
            model_name='aimodels',
            name='open_ai_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
