# Generated by Django 5.1.4 on 2024-12-16 23:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_aimodels_aimodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='duration',
            field=models.IntegerField(verbose_name='Длительность(часы)'),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Стоимость'),
        ),
    ]
