# Generated by Django 5.1.4 on 2024-12-21 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_useraction_created_at_useraction_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='sub_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subscriptiontype'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.telegramuser'),
        ),
    ]
