# Generated by Django 5.1.4 on 2025-01-03 17:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_usersubscription_sub_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
