# Generated by Django 5.1.4 on 2025-02-20 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_usersubscription_options_telegramuser_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserPromocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subscriptiontype')),
            ],
        ),
    ]
