# Generated by Django 5.1.4 on 2025-02-20 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_admintelegramuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUser',
        ),
    ]
