# Generated by Django 5.1.4 on 2025-02-20 14:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_delete_adminuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpromocode',
            options={'verbose_name': 'Промокод', 'verbose_name_plural': 'Промокоды'},
        ),
        migrations.AddField(
            model_name='userpromocode',
            name='promocode_text',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
