version: "3"

services:
  backend:
    build: 
      context: ../backend
      dockerfile: Dockerfile
    container_name: bot
    restart: always
    ports:
      - 80:80
    networks:
      - server
    volumes:
      - logging:/app/DB_volume
      - users_backup:/app/Users_Files
      - users_result_backup:/app/Users_Sent_Files

  bot:
    build: 
      context: ../TelegramBot
      dockerfile: Dockerfile
    container_name: bot-backend
    restart: always
    volumes:
      - db_backup:/app/db
    networks:
      - server
    depends_on:
      - backend


volumes:
  logging:
  users_backup:
  users_result_backup:
  db_backup:
networks:
  server: