version: "3"

services:
  bot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: bot
    restart: always
    volumes:
      - db_backup:/app/DB_volume
      - users_backup:/app/Users_Files
      - users_result_backup:/app/Users_Sent_Files
      
volumes:
  db_backup:
  users_backup:
  users_result_backup: